FROM rust:alpine3.10
ENV RUSTFLAGS="-C target-feature=-crt-static"
WORKDIR /usr/src/rebuilderd
RUN apk add --no-cache musl-dev openssl-dev pkgconfig libsodium-dev
COPY . .
RUN cd worker; cargo build --release

FROM alpine:3.10
RUN apk add --no-cache libgcc openssl libsodium
COPY --from=0 \
    /usr/src/rebuilderd/target/release/rebuilderd-worker \
    /usr/local/bin/
CMD ["rebuilderd-worker"]
