FROM rust:buster
WORKDIR /usr/src/rebuilderd
RUN apt-get update && apt-get install -y libssl-dev libsodium-dev
COPY . .
RUN cd worker; cargo build --release

FROM debian:buster
RUN apt-get update && apt-get install -y libssl-dev libsodium-dev
COPY --from=0 \
    /usr/src/rebuilderd/target/release/rebuilderd-worker \
    /usr/local/bin/
CMD ["rebuilderd-worker"]
