FROM archlinux
WORKDIR /usr/src/rebuilderd
RUN pacman -Suy --noconfirm gcc cargo openssl libsodium
COPY . .
RUN cd worker; cargo build --release

FROM archlinux
RUN pacman -Suy --noconfirm archlinux-repro openssl libsodium
COPY --from=0 \
    /usr/src/rebuilderd/target/release/rebuilderd-worker \
    /usr/local/bin/
CMD ["rebuilderd-worker"]
